### ISSUE TITLE
NameError: name 'indicator' is not defined

### ISSUE THREAD

**Issue by Ni3zam** [Z3NTL3/EfdalHub#1]
```python
Traceback (most recent call last):
  File "efdalhub.py", line 76, in <module>
  File "efdalhub.py", line 39, in main
NameError: name 'indicator' is not defined
[3772] Failed to execute script efdalhub
```
Please fix

**Comment by Z3NTL3** [comment]
> ```python
> Traceback (most recent call last):
>   File "efdalhub.py", line 76, in <module>
>   File "efdalhub.py", line 39, in main
> NameError: name 'indicator' is not defined
> [3772] Failed to execute script efdalhub
> ```
> 
> Please fix

Everything is fixed re-install please to solve
